### ISSUE TITLE
Incompatibility with moto (boto's mocking library)

### ISSUE THREAD

**Issue by Joacchim** [getsentry/responses#554]
### Describe the bug

When using moto.s3 and responses>=0.19 (also tested 0.20), my service's tests are encountering a crash upon accessing some internal methods. As I could not identify why/how we reached that point (due to the mocking mechanism's inherent complexity), I turned to checking versions of my dependencies, and identified responses as the source of the issue (only adding a version enforcement for this pip package fixed the issue).

### Additional context

According to the changelog, some changes were introduced in the registry handling in version `0.19.0`.
As the trace includes the regitries.py file, it sounded like a good candidate, but I didn't dive into the `responses` code, so my guess might be wrong.

### Version of `responses`

0.19.0

### Steps to Reproduce

I tried to dumb down our test case, but I'm unsure whether some bits were necessary, hence still a bit of code, but it should be small enough.

Dependencies are as follows:
 - boto3 (I'm using 1.22.7)
 - moto (I'm using 1.3.16)
 
I can be run with the following command
```shell
$> python -m unittest test.TestS3
```

```python
import asyncio
from moto import mock_s3 # Before boto!
import boto3

from unittest import TestCase


def async_test(co):
    """
    Decorator to do async/await unit testing.
    Event loop is reset for each test.
    """
    def wrapper(*args, **kwargs):
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(co(*args, **kwargs))
        finally:
            loop.close()
    return wrapper


@mock_s3
class TestS3(TestCase):

    def setUp(self):
        self.bucket = 'test'
        self.client = boto3.client('s3', region_name='us-east-1')
        self.client.create_bucket(Bucket=self.bucket)

    def tearDown(self):
        resp = self.client.list_objects(Bucket=self.bucket)
        for obj in resp.get('Contents', []):
            self.client.delete_object(Bucket=self.bucket, Key=obj['Key'])
        self.client.delete_bucket(Bucket=self.bucket)

    @async_test
    async def test_get(self):
        self.assertFalse(False)
        obj = self.client.get_object(Bucket=self.bucket, Key='obj.dat')
        print(obj)

```

### Expected Result

Test should run, with the `boto` API being mocked by `moto` properly.
In the case of the reproducer code, it fails on the s3 GET, without a mysterious trace :)

### Actual Result

Test crashes in the third-party libs (including `moto` and `responses` in the traceback's frames):

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.7/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/home/joa/blade/svs/data_manager/.tox/utest/lib/python3.7/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 633, in run
    self.doCleanups()
  File "/home/joa/blade/svs/data_manager/.tox/utest/lib/python3.7/site-packages/moto/core/models.py", line 98, in wrapper
    self.start(reset=reset)
  File "/home/joa/blade/svs/data_manager/.tox/utest/lib/python3.7/site-packages/moto/core/models.py", line 83, in start
    self.enable_patching()
  File "/home/joa/blade/svs/data_manager/.tox/utest/lib/python3.7/site-packages/moto/core/models.py", line 371, in enable_patching
    match_querystring=False,
  File "/home/joa/blade/svs/data_manager/.tox/utest/lib/python3.7/site-packages/responses/__init__.py", line 603, in add
    self._registry.add(method)
  File "/home/joa/blade/svs/data_manager/.tox/utest/lib/python3.7/site-packages/responses/registries.py", line 53, in add
    response = copy.deepcopy(response)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 247, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.7/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __new__() missing 1 required positional argument: 'source'
```

**Comment by Joacchim** [comment]
Oh, I started from the versions that we had not pinned (not a direct dependency), hence ended on this solution.
Thanks for providing the alternative, which helps me upgrading dependencies on the way :+1:

**Comment by beliaev-maksim** [comment]
@bblommers 
thanks!

**Comment by thenamanpatwari** [comment]
Issue still exists with moto 4.0.11
