### ISSUE TITLE
post method doesn't seem to follow retry mechanism

### ISSUE THREAD

**Issue by obarbier** [getsentry/responses#628]
### Describe the bug

i have the following code which is causing test fail

```
    @responses.activate(registry=registries.OrderedRegistry)
    def test_basic(self):
        import requests
        url = "http://httpstat.us/412"
        rsp1 = responses.post(url, json="Error", status=500)
        rsp2 = responses.post(url, json="Error", status=500)
        rsp3 = responses.post(url, json="Error", status=500)
        rsp4 = responses.post(url, json="Error", status=500)
        rsp5 = responses.post(url, json="Error", status=500)
        t = [rsp1, rsp2, rsp3, rsp4, rsp5]
        responses.add(*t)
        adapter = HTTPAdapter(
            max_retries=Retry(
                total=_RETRY_LOGIC_COUNT,
                backoff_factor=0.1,
                status_forcelist=[412, 500, 502, 503],
                raise_on_status=False,
            )
        )
        session = requests.Session()
        session.mount("http://", adapter)
        r = session.post(url)
        print(r.status_code, r.text)
        assert rsp1.call_count == 1
        assert rsp2.call_count == 1
        assert rsp3.call_count == 1
        assert rsp4.call_count == 1
        assert rsp5.call_count == 1
```

However the same test pass when using get request

```
    @responses.activate(registry=registries.OrderedRegistry)
    def test_basic(self):
        import requests
        url = "http://httpstat.us/412"
        rsp1 = responses.get(url, json="Error", status=500)
        rsp2 = responses.get(url, json="Error", status=500)
        rsp3 = responses.get(url, json="Error", status=500)
        rsp4 = responses.get(url, json="Error", status=500)
        rsp5 = responses.get(url, json="Error", status=500)
        t = [rsp1, rsp2, rsp3, rsp4, rsp5]
        responses.add(*t)
        adapter = HTTPAdapter(
            max_retries=Retry(
                total=_RETRY_LOGIC_COUNT,
                backoff_factor=0.1,
                status_forcelist=[412, 500, 502, 503],
                raise_on_status=False,
            )
        )
        session = requests.Session()
        session.mount("http://", adapter)
        r = session.get(url)
        print(r.status_code, r.text)
        assert rsp1.call_count == 1
        assert rsp2.call_count == 1
        assert rsp3.call_count == 1
        assert rsp4.call_count == 1
        assert rsp5.call_count == 1
```

### Version of `responses`

0.20.0

### Steps to Reproduce

```python
    @responses.activate(registry=registries.OrderedRegistry)
    def test_basic(self):
        import requests
        url = "http://httpstat.us/412"
        rsp1 = responses.post(url, json="Error", status=500)
        rsp2 = responses.post(url, json="Error", status=500)
        rsp3 = responses.post(url, json="Error", status=500)
        rsp4 = responses.post(url, json="Error", status=500)
        rsp5 = responses.post(url, json="Error", status=500)
        t = [rsp1, rsp2, rsp3, rsp4, rsp5]
        responses.add(*t)
        adapter = HTTPAdapter(
            max_retries=Retry(
                total=_RETRY_LOGIC_COUNT,
                backoff_factor=0.1,
                status_forcelist=[412, 500, 502, 503],
                raise_on_status=False,
            )
        )
        session = requests.Session()
        session.mount("http://", adapter)
        r = session.post(url)
        print(r.status_code, r.text)
        assert rsp1.call_count == 1
        assert rsp2.call_count == 1
        assert rsp3.call_count == 1
        assert rsp4.call_count == 1
        assert rsp5.call_count == 1

```

### Expected Result

the test should pass

### Actual Result

Failure
Traceback (most recent call last):
  File "<PATH>", line 218, in wrapper
    return func(*args, **kwargs)
  File "<PATH>", line 118, in test_basic
    assert rsp2.call_count == 1
AssertionError

**Comment by obarbier** [comment]
@beliaev-maksim  thank you that was a great insight
